apiVersion: v1
kind: Service
metadata:
  name: gotodo-svc
spec:
  ports:
  - port: 80
  selector:
    app: gotodo-app
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gotodo-app
spec:
  selector:
    matchLabels:
      app: gotodo-app
  replicas: 1 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: gotodo-app
    spec:
      containers:
      - name: gotodo-ctn
        image: chunliu/gotodoimg:v0.1.0
        ports:
        - containerPort: 80
