apiVersion: v1
kind: Service
metadata: 
  name: gotodo-backend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: gotodo-app
    tier: gotodo-backend
spec:
  selector:
    tier: gotodo-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotodo-app
    tier: gotodo-backend
  name: gotodo-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      tier: gotodo-backend
  template:
    metadata:
      labels:
        app: gotodo-app
        tier: gotodo-backend
    spec:
      containers:
      - image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        name: gotodo-be-cnt
        ports:
        - containerPort: 8080
        env:
          - name: GOTODO_VERSION
            valueFrom:
              configMapKeyRef:
                name: gotodo-cm
                key: be-version
        resources: {}
