apiVersion: v1
kind: Service
metadata: 
  name: gotodo-frontend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: gotodo-app
    tier: gotodo-frontend
spec:
  selector:
    tier: gotodo-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotodo-app
    tier: gotodo-frontend
  name: gotodo-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      tier: gotodo-frontend
  template:
    metadata:
      labels:
        app: gotodo-app
        tier: gotodo-frontend
    spec:
      containers:
      - image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        name: gotodo-fe-cnt
        ports:
        - containerPort: 80
        resources: {}
